create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    num_red_ml integer not null default 0,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    gold integer not null default 100,
    potion_capacity integer not null default 1,
    ml_capacity integer not null default 1,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    sku text not null,
    quantity integer not null,
    price integer not null,
    red integer not null,
    green integer not null,
    blue integer not null,
    dark integer not null,
    constraint potion_inventory_pkey primary key (sku)
  ) tablespace pg_default;

create table
  public.customers (
    id bigint generated by default as identity not null,
    visited_at timestamp with time zone not null default now(),
    name text not null,
    class text not null,
    level integer not null,
    constraint customers_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    customer_id bigint not null,
    constraint carts_pkey primary key (id),
    constraint carts_customer_id_fkey foreign key (customer_id) references customers (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id bigint not null,
    sku text not null,
    quantity integer not null,
    constraint cart_items_pkey primary key (cart_id, sku),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_sku_fkey foreign key (sku) references potion_inventory (sku)
  ) tablespace pg_default;

  INSERT INTO global_inventory DEFAULT VALUES;